version: '3.4'
services:
  postgres:
    image: postgres:12.5
    restart: always
    stop_grace_period: 30s
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
